version: '3'

services:

  backend:
    build: ./server
    ports:
      - "4000:4000"
    restart: always

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
 